---
- name: Configure VLAN
  hosts: cisco
  gather_facts: false
  tasks:
    - name: confguring vlan
      ios_vlans:
        config:
          - vlan_id: 111
            name: "test_vlan"
            state: active
    - name: delete vlan
      ios_vlans:
        state: deleted
        config:
          - vlan_id: 111
            name: "test_vlan"
            state: deleted
      tags:
        - deletevlan
#Configure interface
    - name: configure interface
      ios_interfaces:
        config:
          - name: "{{ interface }}"
            description: "{{ description }}"
            enabled: "{{ enabled }}"
            speed: "{{ speed }}"
            mtu: "{{ mtu }}"
        state: "{{ state }}"
      tags:
        - never
    - name: create camtest vlan
      cisco.ios.ios_vlans:
        state: merged
        config:
          - name: fddinet-default
            vlan_id: 1004
            state: active
            shutdown: disabled
      tags:
        - never
    - name: Create a new user
      cisco.ios.ios_user:
        name: ansible
        configured_password: "ansible"
        password_type: password
        state: present
      tags:
        - never
