---
- name: Create an incident in ServiceNow
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
    incident_description: 'test incident'
    github_repo: https://github.com/kamlendu1982/ServiceNowAAP.git
    sn_urgency: low
    sn_impact: low
  tasks:
  - name: create a folder
    ansible.builtin.file:
      path: /runner/tmpgit/
      state: directory
      mode: 0755
  - name: "Clone the required repo"
    environment:
      - GIT_SSL_NO_VERIFY: false 
    ansible.builtin.git:
      repo: "{{ github_repo | ansible.builtin.regex_replace('(https?://)','\\1'+github_api_user+':'+github_api_token+'@') }}"
      #repo: https://github.com/kamlendu1982/ServiceNowAAP.git 
      dest: "/runner/tmpgit/"
