---
- name: Create an incident in ServiceNow
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
    incident_description: 'cisco poc incident'
    sn_urgency: low
    sn_impact: low
  tasks:
  - name: Create an incident in ServiceNow
    servicenow.itsm.incident:
      state: new
      description: "{{ sn_description | default(omit) }}"
      short_description: "{{ incident_description }}"
      caller: admin
      urgency: "{{ sn_urgency }}"
      impact: "{{ sn_impact }}"
      other:
        u_operating_system: "{{ os | default(omit) }}"
        u_ip_address: "{{ ip_addr | default(omit) }}"
        u_device_name: "{{ inventory_hostname | default(omit) }}"
        u_device_typs: "cisco"
        u_ticket_comment: ""
    register: new_incident
    delegate_to: localhost
  - debug:
      var: new_incident.record.number 

  - set_fact: 
      incident_number: "{{ new_incident.record.number }}"
  - debug:
      var: incident_number
