---
- name: deleting host from host metrics 
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
    controller_url: "student1.7qsfr.example.opentlc.com"
    #host_delete: "192.168.122.56"
    #ansible_user: admin
    #ansible_password: admin123
  tasks:
    - name: check reachablity
      ansible.builtin.uri:
        url: "https://{{ controller_url }}"
        validate_certs: false

    - name: get the host id
      ansible.builtin.uri:
        #url: https://controller.kam.home.com/api/v2/hosts/?search=host_delete
        #url: "https://192.168.122.216/api/v2/host_metrics/?search={{ host_delete }}"
        url: "https://{{ controller_url }}/api/v2/host_metrics/?search={{ host_delete }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: GET
        headers:
          Content-Type: application/json
          Authorization: "Basic {{ (ansible_user + ':' + ansible_password) | b64encode }}"
          #Authorization: "Basic {{ (ansible_user + ':' + ansible_password) | b64encode }}"
        validate_certs: false
      register: host_id
      delegate_to: localhost

    - debug:
        var: host_id.json.results[0].id

    - name: delete the host from host metrices
      ansible.builtin.uri:
        #url: https://controller.kam.home.com/api/v2/host_metrics/"{{ host_id.results.id }}"/
        #url: https://192.168.122.216/api/v2/host_metrics/"{{ host_id.results.id }}"/
        url: "https://{{ controller_url }}/api/v2/host_metrics/{{ host_id.json.results[0].id }}/"
        method: DELETE
        headers:
          Content-Type: application/json
          Authorization: "Basic {{ (ansible_user + ':' + ansible_password) | b64encode }}"
        validate_certs: false
        status_code: 204
      delegate_to: localhost
      tags:
        - never
        - delete_host
