---
- name: execute powershell scripts
  hosts: all
  vars:
    triggerapp: "AAP"

  tasks:
    - name: execute the powershell script
      ansible.windows.win_shell: "{{ path_ps_script }}" >> C:\Temp-Ansible\temp.txt
      #delegate_to: pw02xda9.am.cpb.com
      register: outps

    - name: print out from powershell script
      debug:
       msg: "{{ outps.stdout_lines }}"
