---
- name: execute powershell scripts
  hosts: localhost
  vars:
    triggerapp: "AAP"

  tasks:
    - name: execute the powershell script
      ansible.windows.win_shell: "{{ path_ps_script }}"
      delegate_to: localhost
      register: outps

    - name: print out from powershell script
      debug:
       msg: "{{ outps.stdout_lines }}"
