- name: Hello World Sample
  hosts: localhost
  #ignore_unreachable: true
  gather_facts: true
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! the first password is {{ password1 }}"
      no_log: true
    - name: not ignore Message
      debug:
        msg: "not ignore Hello World! the second password is {{ password2 }}"
