---
- hosts: all
  gather_facts: false
  tasks:
    - name: "Retrieve hostname"
      changed_when: false
      ansible.builtin.command:
        cmd: hostname
      register: hostname_output

    - name: "Debug hostname"
      ansible.builtin.debug:
        var: hostname_output.stdout

