---
- name: update an incident in ServiceNow
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
    incident_description: 'cisco poc incident'
    sn_urgency: low
    sn_impact: low
  tasks:
  - debug:
      var: device_payload 
  - name: update an incident in ServiceNow
    servicenow.itsm.incident:
      state: in_progress
      attachments:
        - path: /tmp/cpu_data_cisco.txt
      number: "{{ incident_number }}"
      other:
        u_operating_system: "{{ os | default(omit) }}"
        u_ip_address: "{{ ip_addr | default(omit) }}"
        u_device_name: "{{ inventory_hostname | default(omit) }}"
        u_device_typs: "cisco"
        u_ticket_comment: "{{ device_payload }}"
    delegate_to: localhost
